# Generated by Django 3.2.3 on 2021-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
